# Generated by Django 4.2.24 on 2025-12-26 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0105_processedwebhook'),
        ('db', '0112_auto_20251124_0603'),
    ]

    operations = [
    ]
