# Generated by Django 4.2.27 on 2026-01-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0113_merge_0105_processedwebhook_0112_auto_20251124_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='plan',
            field=models.CharField(choices=[('FREE', 'FREE'), ('BUSINESS', 'BUSINESS'), ('ENTERPRISE', 'ENTERPRISE')], default='FREE', max_length=20),
        ),
    ]
